
version: '2.1'
services:
  database:
    container_name: main-server-database
    image: bitnami/postgresql:13.14.0
    environment:
      - POSTGRES_USER=bogdan
      - POSTGRES_PASSWORD=bogdan
      - POSTGRES_DB=server_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - ./data.sql:/docker-entrypoint-initdb.d/2-data.sql
      - /home/user1/main-server/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      backend:
        aliases:
          - "database"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  main-server:
    image: patseev1987/main-server:latest
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://database/server_db
    networks:
      backend:
        aliases:
          - "main-server"
    restart: always

networks:
  backend:
    driver: bridge
