spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: bogdan
    password: bogdan
    url: jdbc:postgresql://localhost:5432/server_db
  application:
    name: server-for-android-application
  jpa:
    properties:
      hibernate:
        show_sql: true
        hbm2ddl:
          auto: update




jwt:
  token:
    validity: 100
  secret: united-engine-corporation

server:
  port: 8080
